add routers
xingyunzh/Camps pull request #2
Opened 2016-09-23 07:48 UTC by rayzhang-xingyunzh

# Conflicts:
#	app.js
#	controllers/demoController.js
#	package.json
#	routes/router.js

2016-09-24 15:00 UTC, williamyu-xingyunzh commented on models/task.js
>  		ref:'TeamMember'
Why is it 'TeamMember', other than 'User' here?

2016-09-24 15:07 UTC, williamyu-xingyunzh commented on routes/accessControl.js
> +module.exports = function(app){
[blocker]This is definitely wrong here: 

1. Controller should not do any routing chain changes. Move this logic to routes module.
2. You should not apply any route specific info to app directly. You should apply it to rootRouter instead. This code here breaks the contextRoot feature.

2016-09-24 15:09 UTC, williamyu-xingyunzh commented on routes/accessControl.js
> +		var tokenString = req.body.token;
[b]The token should be part of header of the request, not the body here.
You should not ask every request to be post and have a body field "token".

2016-09-24 15:15 UTC, williamyu-xingyunzh commented on util/shared/tokenHelper.js
> +
The token logic is definitely not just a "util" method. It should be in authentication module. Util is for just general method, like string, math, wrapper, pure convenient method. It should not contain any business logic. 
Especially secret is very important and specific here.

2016-09-24 15:23 UTC, williamyu-xingyunzh requested changes
Please clarify/reply or accept/implement all the comments in this review.

Apart from business questions/coments, here are 2 general comments for programing perspecitve:
1. Abuse of "State Machine" method.
2. Abuse of "util"

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on controllers/userController.js
> +	function stateMachine(err,toState){
[non-blocker comment] I don't see any benefit to introduce state machine here. Check param is very ordinary action before perform other functional logic.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on controllers/userController.js
> +				case STATE_IS_FRIST_TIME:
Are the states below reachable?

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/asset.js
> +		date:Date
Version should be simple string. If you want to add a create_date info, you can have a separate field to store it.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/idea.js
>  		ref:'Player'
Since player is removed, this ref should be changed as well.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/sprint.js
> +	backlog:[{
"backlog" is not accurate here. It is only for the prioritized set of all the stories.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/sprint.js
> +		ref:'Tasks'
Do you have this schema?  's' is typo here? Tasks should be grouped and under some specific story.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/team.js
>  var teamSchema = Schema({
where is the uid we discussed, which is to identify the inheritance of the team.

2016-09-24 15:23 UTC, williamyu-xingyunzh commented on models/team.js
> +	activeDate:Date
Do you need both create date and active date? What's the difference you think?

2016-09-25 01:32 UTC, morrieati commented on models/idea.js
>  		ref:'Player'
Should the `Schema.Type.ObjectId` be `Schema.Types.ObjectId`?

2016-09-26 01:52 UTC, rayzhang-xingyunzh commented on controllers/userController.js
> +				case STATE_IS_FRIST_TIME:
fixed

2016-09-26 01:53 UTC, rayzhang-xingyunzh commented on models/asset.js
> +		date:Date
1. A string? not number?
2. a version date is the date for the specific version

2016-09-26 01:53 UTC, rayzhang-xingyunzh commented on models/idea.js
>  		ref:'Player'
fixed

2016-09-26 01:55 UTC, rayzhang-xingyunzh commented on models/sprint.js
> +	backlog:[{
fixed

2016-09-26 01:57 UTC, rayzhang-xingyunzh commented on models/sprint.js
> +		ref:'Tasks'
It is a typo.fixed

2016-09-26 01:59 UTC, rayzhang-xingyunzh commented on models/team.js
> +	activeDate:Date
I was thinking about the create date of the inherited team, but maybe we can use the earliest activeDate as the create date. How do you think @williamyu-xingyunzh ?

2016-09-26 02:09 UTC, williamyu-xingyunzh commented on models/asset.js
> +		date:Date
yes, version should be a simple string as I mentioned. Don't make simple complex.

2016-09-26 02:11 UTC, williamyu-xingyunzh commented on models/team.js
> +	activeDate:Date
Yeah, please ensure the data is not duplicated in your model.

2016-09-26 02:17 UTC, rayzhang-xingyunzh commented on controllers/userController.js
> +	function stateMachine(err,toState){
fixed

2016-09-26 02:17 UTC, rayzhang-xingyunzh commented on models/team.js
>  var teamSchema = Schema({
teamId

2016-09-26 02:18 UTC, rayzhang-xingyunzh commented on routes/accessControl.js
> +module.exports = function(app){
fixed

2016-09-26 02:30 UTC, rayzhang-xingyunzh commented on models/task.js
>  		ref:'TeamMember'
fixed

2016-09-27 05:34 UTC, williamyu-xingyunzh approved these changes
version in asset.js is not fixed.
There are stills lots of typo. 
Please unit test your code before writing more.  agile way of work is making a bit, testing the bit, then another bit. Do not do it all in all.

2016-09-27 05:34 UTC, williamyu-xingyunzh commented on models/comment.js
> +		type:Schema.types.ObjectId,
Capital “T”?

2016-09-27 05:34 UTC, williamyu-xingyunzh commented on models/discussMinutes.js
> +		type:Schema.types.ObjectId,
Types
Your editor did not work well to help you. You should make it work.

2016-09-27 05:34 UTC, williamyu-xingyunzh commented on models/sprint.js
>  	task:{
only one task allowed in one sprint?

2016-09-27 05:34 UTC, williamyu-xingyunzh commented on models/task.js
>  	duedate:Date,
add effort field.

2016-09-27 05:35 UTC, merged