bug fix & add router
xingyunzh/Camps pull request #4
Opened 2016-09-25 16:12 UTC by morrieati

2016-09-26 02:02 UTC, williamyu-xingyunzh commented on routes/router.js
> +    rootRouter.use('/message');
You need to associate messageRouter to this path.
say, rootRouter.use('/message', messageRouter);

2016-09-26 02:03 UTC, williamyu-xingyunzh commented on routes/router.js
>  var messageController = require('../controllers/messageController');
messageController is no longer needed here.  Let demoController be kept here. I will remove it eventually.

2016-09-26 02:07 UTC, williamyu-xingyunzh requested changes
You'd better unit test your change before submitting the request.
Btw, you can submit part of our work, but please ensure that is your intent, say adding "TODO","To be continued", or "TBD" comments there for unfinished part.

2016-09-26 02:07 UTC, williamyu-xingyunzh commented on routes/messageRouter.js
> +messageRouter.post('/sending', messageController.sendMessage);
Seems you have not exported via "module.exports". So how can you get it via "require" in router.js?

2016-09-28 01:47 UTC, morrieati commented
fixed

2016-09-28 06:35 UTC, williamyu-xingyunzh commented
Hi Morris，
I'm not able to merge your pull request. because "This branch has conflicts that must be resolved".
You need update your branch with latest master's code, and resolve conflicts well.

2016-09-28 09:31 UTC, morrieati commented
conflicts resolved

2016-09-28 09:40 UTC, morrieati commented
conflicts resolved

2016-09-28 12:38 UTC, williamyu-xingyunzh approved these changes
Since you've add a message page in ui, just keep it for test. Please touch /public/\* as litttle as possible. You can use Postman or other RESTful tools to test your backend service.

2016-09-28 12:40 UTC, merged